### ISSUE TITLE
Slot unresponsive to mouse clicks

### ISSUE THREAD

**Issue by abluescarab** [abluescarab/tModLoader-WingSlot#2]
From the Terraria Forums, [Zauber Paracelsus said](http://forums.terraria.org/index.php?threads/abluescarabs-mods.47835/#post-1101846):

> I've installed this mod, and I found that once a wing is placed into the slot, it cannot be removed except by right-clicking a different wing to replace it. At first I thought it was because it was a wing from a mod, but after replacing it with a vanilla wing, I still have the problem. As well, the visibility icon for the wing slot is unresponsive, and is off by default. Reading the changelog above, perhaps the unresponsiveness bug was not fully fixed? Or perhaps the mod just needs to be updated for Terraria 1.3

**Comment by Rahmiel** [comment]
I can semi-confirm this. The issue isn't that its completely unresponsive, more that it is finicky. I was able to move the wings after a lot of clicking, the slot just seems a bit unresponsive. I would suggest possibly moving the wing slot to the bottom of the accessory slot list under where the extra accessory would normally be, similar to how More Accessories+ did it back in the day.

**Comment by abluescarab** [comment]
Would it be possible for you to take a video of the behavior? I can't replicate it on my machine, so I'm not sure how to fix it. Try [Open Broadcaster Software](https://obsproject.com/) if you're willing and you don't know what to use.

**Comment by zauberparacelsus** [comment]
No amount of clicking will get a response out of the wing slot for me.

I have to wonder though, if it may be due to a version issue with the .Net framework and/or Mono?

I'm running Mono 4.6.1 on my machine.  I don't recall off-hand what version of the .Net framework is running on my windows drive, but I think it is either 4.6.x or 4.5.x.

**Comment by abluescarab** [comment]
@zauberparacelsus If you're running Mono to play Terraria, then are you on Linux? I would have to install a Linux VM on my computer and debug the mod in that, which isn't a big deal but is a bit out of my knowledge range. It's midterm week at the moment so I can get to it when I have some free time. Worse comes to worse, I can implement some keybinds to remove the active wing/vanity wing.

**Comment by zauberparacelsus** [comment]
@abluescarab Yeah, I'm on Linux.  64bit Ubuntu to be precise.  IIRC, the issue repro's on my Windows 8.1 drive as well (I dual boot).

I am not sure that a VM is workable.  Hardware acceleration won't work on VMs unless your computer's motherboard has a specific hardware feature (IOMMU on AMD boards, VT-d on Intel boards), and when doing so the host machine loses access to graphics, since the host and VM can't use them simultaneously.

It would probably be easier to dual-boot, though my recommendation in such a case would be to put the Linux partition on a separate hard drive, so you don't have to deal with Linux overwriting the Windows boot loader.

Then again, full hardware acceleration may not be necessary.  Terraria's system requirements don't need very strong graphics acceleration, so its rendering may primarily be CPU bound.

**Comment by abluescarab** [comment]
@zauberparacelsus I've had issues with dual-boot in the past with my current hardware. I'm not sure about the accelerated hardware issue but I don't think I've ever run into it. I have an Intel i5 on both my desktop and laptop, so I'll give it a go and see what happens. As I've said before, I can't reproduce the issue on my local machine, but I have Windows 10 on my computer.

**Comment by zauberparacelsus** [comment]
I just booted up my windows partition, and I can confirm that the issue still occurs there.

**Comment by abluescarab** [comment]
@zauberparacelsus Does this bug still occur with the latest version of WingSlot?

**Comment by Lothrik** [comment]
I have the same problem with the latest version. Oddly. I'm able to remove the wing slot item (somewhat) easier when sprinting and spam left clicking. Removing them while stationary is near impossible.

**Comment by QuiOui** [comment]
I've had the same issue, seems to be a problem with autopause.  When it's on I can't click on the wings, with it disabled the slot works.

**Comment by zauberparacelsus** [comment]
@abluescarab Sorry, forgot to respond.  The bug still occurs at the time of this writing, with the latest versions of tModLoader and Wingslot.

I'm going to list off the mods I've got installed, just in case it is a conflict:

- Thorium
- Boss Checkless
- Dushy's Upgrade
- Loot Bags
- ZeldaRupee
- Tremor Mod Remastered
- Spirit Mod
- Learn by Doing
- Wing Slot
- Zoaklen Mod
- Wormholes
- Cheat Sheet
- imkSushi Mod
- Terra's Wing Compilation
- Worldgen Previewer

**Comment by zauberparacelsus** [comment]
Oh, and equipping vanity wings doesn't work either.  I hit Shift-RightClick, and it just swaps out the normal wings.

**Comment by zauberparacelsus** [comment]
With the latest update to this mod, things are now working.  The only issue I see is that when I pick up a wing, it won't let me manually go to the utility slots page, but I can just use rightclick and shift-rightclick to put on wings and vanity wings.

Oh, and the secondary issue with the wing slot's Eye icon being unclickable has been resolved as well!

**Comment by abluescarab** [comment]
@zauberparacelsus Sorry, I wrote out a reply last night and somehow never posted it. I'm so glad it works now! The issue with equipment pages is something I can't fix unless an override is added to tModLoader, so I'm afraid everyone has to deal with that one. That problem is the only reason there's a complicated set of hotkeys.

Thanks for being so patient with me while I try to iron out the bugs in this mod!
