### ISSUE TITLE
Wing stats

### ISSUE THREAD

**Issue by ReCONman259** [abluescarab/tModLoader-WingSlot#28]
The wings once added to the wing slot, doesn't add any stats, such as Warding or mencing.

**Comment by abluescarab** [comment]
Duplicate of #26. Have you updated to the latest Wing Slot?

**Comment by ReCONman259** [comment]
The last time I had this mod installed the issue was there, but now the mod it fixed in that sense. Thank you very much, great mod, adds more options to have more accessories

**Comment by abluescarab** [comment]
Thank you for using Wing Slot! I'm glad you like it! Closing issue.

**Comment by Revemohl** [comment]
Didn't want to open a new issue because this is directly related to this one. Would it be possible to add a config option for enabling or disabling wing prefixes, then? I've always felt that getting one more modifier thanks to the wing slot was a bit unbalanced, and I thought that the new behavior was intended.
